spinner fixes

diff --git a/bin/spinner b/bin/spinner
--- a/bin/spinner
+++ b/bin/spinner
@@ -1,33 +1,64 @@
 #!/bin/zsh
-# - https://unix.stackexchange.com/a/565551/456475
-## Shows a spinner while another command is running ##
+# Shows a spinner while another command is running.
+# Usage: spinner sleep 10
+# With variant: SPINNER=4 spinner cp src dst
 #
-# CLI use:
-#  spinner sleep 10
-#
-# To call it within another script you can source it:
-#  $(dirname "$0")/spinner.sh
-#  sleep 10 & spinner $!
-#
-# Or prefix known long running commands with an alias:
-#  alias rm="spinner rm"
+# ID map (for aliases):
+#   0  -\|/           classic
+#   1  ▁▂▃            bar pump
+#   2  ▖▘▝▗           quadrant
+#   3  ◢◣◤◥           corners
+#   4  ╹┗┣╋           box drawing
+#   5  pancake flip
+#   6  ┫┛┻┗           box drawing 2
+#   7  ╯╰╭╮           rounded
+#   8  ╸╹╺╻           thick lines
+#   9  ▌▀▐▄           block rotation
+#  10  ╸╹╺╻           apple logo
+#  11  ◜◠◝◞◟          circle
+#  12  ▁▂▃▄▅          full block seq
+#  13  binary         8-bit
+#  14  ▹▹▹▸           running arrow
+#  15  ▱▰             bar fill 2
+#  16  ▱▰             bar fill 3
+#  17  ⠁⠂⠄            braille rotation
+#  18  ⠁⠂⠄⠂          braille simple
+#  19  ⣾⣽⣻            braille wheel
+#  20  ⠁⠃⠇⡇           braille accumulate
+#  21  ▁▁▁████        fade
+#  22  ▐⠂▌            dot in bar
+#  23  █▁             build-up wave
+#  24  ↑↗→↘           compass
+#  25  ⚀⚁⚂⚃           dice roll
+#  26  ✶✷✸✹           star burst
+#  27  ▁▇█▄           pulse
+
+# ── non-interactive fast path ──
+# If stdout is not a TTY or TERM is unset, run the command directly so escape
+# sequences never corrupt a pipe or data stream.
+if [[ ! -t 1 || -z "$TERM" ]]; then
+  exec "$@"
+fi
+
+if [[ $# -eq 0 ]]; then
+  echo "usage: spinner <command> [args...]" >&2
+  exit 1
+fi
 
 function cleanup() {
-  tput cnorm
-
-  echo -en "\033[2K\r"
+  tput cnorm > /dev/tty 2>/dev/null
+  printf "\r\033[K" > /dev/tty 2>/dev/null
 }
 trap cleanup EXIT
 
 function spinner() {
-  # make sure we use non-unicode character type locale
-  # (that way it works for any locale as long as the font supports the characters)
   local LC_CTYPE=C
+  local sid=$1
+  local pid=$2
 
-  local sid=$1 # Spinner Id to use
-  local pid=$2 # Process Id of the previous running command
+  [[ "$sid" =~ ^[0-9]+$ ]] || sid=0
 
-  case $((${sid} % 33)) in
+  case $((sid % 28)) in
   0)
     local spin='-\|/'
     local charwidth=1
@@ -37,150 +68,132 @@ function spinner() {
     local charwidth=3
     ;;
   2)
-    local spin="▉▊▋▌▍▎▏▎▍▌▋▊▉"
+    local spin='▖▘▝▗'
     local charwidth=1
     ;;
   3)
-    local spin='▖▘▝▗'
-    local charwidth=3
-    ;;
-  4)
-    local spin='┤┘┴└├┬'
+    local spin='◢◣◤◥'
     local charwidth=1
     ;;
-  5)
-    local spin='◢◣◤◥'
-    local charwidth=3
-    ;;
-  6)
-    local spin="●∙∙∙●∙∙∙●∙●∙"
-    local charwidth=3
-    ;;
-  7)
+  4)
     local spin='╹┗┣╋┳┏╻┓┫╋┻┛'
     local charwidth=1
     ;;
-  8)
+  5)
     local spin="___-\`\`'´-___-´´'\`-"
     local charwidth=1
     ;;
-  9)
+  6)
     local spin='┫┛┻┗┣┏┳┓'
     local charwidth=1
     ;;
-  10)
+  7)
     local spin='╯╰╭╮'
     local charwidth=1
     ;;
-  11)
+  8)
     local spin='╸╹╺╻'
     local charwidth=1
     ;;
-  12)
+  9)
     local spin='▌▀▐▄'
     local charwidth=1
     ;;
-  13)
+  10)
     local spin='╸╹╺╻        '
     local charwidth=1
     ;;
-  14)
-    local spin=''
-    local charwidth=1
-    ;;
-  15)
-    local spin=''
-    local charwidth=1
-    ;;
-  16)
+  11)
     local spin='◜◠◝◞◟◡◌○◎◷◶◵◵◴◔◑◒◐◓◑◕◉●◕◑◒◐◓◔◎○◌'
     local charwidth=1
     ;;
-  17)
+  12)
     local spin='▁▂▃▄▅▆▇█▉▊▋▌▍▎▏░▒▓▔▖▗▘▙▚▛▜▝▞▟▀█▄▌▐▀'
     local charwidth=1
     ;;
-  18)
+  13)
     local spin=`binaryArray=({0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1}) ; printf %s "${binaryArray[@]}" $'\n'`
     local charwidth=8
     ;;
-  19)
+  14)
     local spin="▹▹▹▹▹▸▹▹▹▹▹▸▹▹▹▹▹▸▹▹▹▹▹▸▹▹▹▹▹▸"
     local charwidth=5
     ;;
-  20)
-    local spin="▰▱▱▱▱▱▱▰▰▱▱▱▱▱▰▰▰▱▱▱▱▰▰▰▰▱▱▱▰▰▰▰▰▱▱▰▰▰▰▰▰▱▰▰▰▰▰▰▰▰▱▱▱▱▱▱"
-    local charwidth=7
-    ;;
-  21)
+  15)
     local spin="▱▱▱▱▱▱▱▱▱▱▰▱▱▱▱▱▰▰▰▱▱▱▰▰▰▰▰▱▰▰▰▰▰▰▰▱▰▰▰▰▰▱▱▱▰▰▰▱▱▱▱▱▰▱▱▱"
     local charwidth=7
     ;;
-  22)
+  16)
     local spin="▱▱▰▰▰▱▱▱▱▱▰▰▰▱▱▱▱▱▰▰▰▱▱▱▱▱▰▰▱▱▱▱▱▱▰▱▱▱▱▱▰▰▱▱▱▱▰▰▰▱▱▱▰▰▰▱▱▱▰▰▰▱▱▱▰▰▰▱▱▱▰▰▰▱▱▱▱▰▰▱▱▱▱▱▰▱▱▱▱▱▱▰▰▱▱▱▱▱▰▰▰▱▱▱▱▱▰▰▰▱▱▱"
     local charwidth=7
     ;;
-  23)
+  17)
     local spin='⠁⠂⠄⡀⢀⠠⠐⠈'
     local charwidth=1
     ;;
-  24)
+  18)
     local spin="⠁⠂⠄⠂"
     local charwidth=1
     ;;
-  25)
+  19)
     local spin='⣾⣽⣻⢿⡿⣟⣯⣷'
     local charwidth=1
     ;;
-  26)
-    local spin='⡀⡁⡂⡃⡄⡅⡆⡇⡈⡉⡊⡋⡌⡍⡎⡏⡐⡑⡒⡓⡔⡕⡖⡗⡘⡙⡚⡛⡜⡝⡞⡟⡠⡡⡢⡣⡤⡥⡦⡧⡨⡩⡪⡫⡬⡭⡮⡯⡰⡱⡲⡳⡴⡵⡶⡷⡸⡹⡺⡻⡼⡽⡾⡿⢀⢁⢂⢃⢄⢅⢆⢇⢈⢉⢊⢋⢌⢍⢎⢏⢐⢑⢒⢓⢔⢕⢖⢗⢘⢙⢚⢛⢜⢝⢞⢟⢠⢡⢢⢣⢤⢥⢦⢧⢨⢩⢪⢫⢬⢭⢮⢯⢰⢱⢲⢳⢴⢵⢶⢷⢸⢹⢺⢻⢼⢽⢾⢿⣀⣁⣂⣃⣄⣅⣆⣇⣈⣉⣊⣋⣌⣍⣎⣏⣐⣑⣒⣓⣔⣕⣖⣗⣘⣙⣚⣛⣜⣝⣞⣟⣠⣡⣢⣣⣤⣥⣦⣧⣨⣩⣪⣫⣬⣭⣮⣯⣰⣱⣲⣳⣴⣵⣶⣷⣸⣹⣺⣻⣼⣽⣾⣿'
+  20)
+    local spin='⠁⠃⠇⡇⡏⡟⡿⣿⡿⡟⡏⡇⠇⠃'
     local charwidth=1
     ;;
-  27)
-    local spin="( ●    )(  ●   )(   ●  )(    ● )(     ●)(    ● )(   ●  )(  ●   )( ●    )(●     )"
-    local charwidth=8
-    ;;
-  28)
-    local spin="[    ][=   ][==  ][=== ][====][ ===][  ==][   =][    ]"
-    local charwidth=6
-    ;;
-  29)
-    local spin="[    ][=   ][==  ][=== ][====][ ===][  ==][   =][    ][   =][  ==][ ===][====][=== ][==  ][=   ]"
-    local charwidth=6
-    ;;
-  30)
+  21)
     local spin="▁▁▁█████████▁▁█████████▁▁█████████▁▁█████████▁▁█████████▁▁▓████████▁▁▓████████▁▁▒████████▁▁▒████████▁▁░████████▁▁░████████▁▁▁████████▁▁▁████████▁▁▁████████▁▁▁▓███████▁▁▁▓███████▁▁▁▒███████▁▁▁▒███████▁▁▁░███████▁▁▁░███████▁▁▁▁███████▁▁▁▁███████▁▁▁▁███████▁▁▁▁▓██████▁▁▁▁▓██████▁▁▁▁▒██████▁▁▁▁▒██████▁▁▁▁░██████▁▁▁▁░██████▁▁▁▁▁██████▁▁▁▁▁██████▁▁▁▁▁██████▁▁▁▁▁▓█████▁▁▁▁▁▓█████▁▁▁▁▁▒█████▁▁▁▁▁▒█████▁▁▁▁▁░█████▁▁▁▁▁░█████▁▁▁▁▁▁█████▁▁▁▁▁▁█████▁▁▁▁▁▁█████▁▁▁▁▁▁▓████▁▁▁▁▁▁▓████▁▁▁▁▁▁▒████▁▁▁▁▁▁▒████▁▁▁▁▁▁░████▁▁▁▁▁▁░████▁▁▁▁▁▁▁████▁▁▁▁▁▁▁████▁▁▁▁▁▁▁████▁▁▁▁▁▁▁▓███▁▁▁▁▁▁▁▓███▁▁▁▁▁▁▁▒███▁▁▁▁▁▁▁▒███▁▁▁▁▁▁▁░███▁▁▁▁▁▁▁░███▁▁▁▁▁▁▁▁███▁▁▁▁▁▁▁▁███▁▁▁▁▁▁▁▁███▁▁▁▁▁▁▁▁▓██▁▁▁▁▁▁▁▁▓██▁▁▁▁▁▁▁▁▒██▁▁▁▁▁▁▁▁▒██▁▁▁▁▁▁▁▁░██▁▁▁▁▁▁▁▁░██▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁▓█▁▁▁▁▁▁▁▁▁▓█▁▁▁▁▁▁▁▁▁▒█▁▁▁▁▁▁▁▁▁▒█▁▁▁▁▁▁▁▁▁░█▁▁▁▁▁▁▁▁▁░█▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▓▁▁▁▁▁▁▁▁▁▁▓▁▁▁▁▁▁▁▁▁▁▒▁▁▁▁▁▁▁▁▁▁▒▁▁▁▁▁▁▁▁▁▁░▁▁▁▁▁▁▁▁▁▁░▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁‼▁▁▁▁▁▁▁▁▁▁▁‼▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▆▁▁▁▁▁▁▁▁∞▁▁▅▁▁▁▁▁▁▁▁∞▁▁▄▁▁▁▁▁▁▁▁∞▁▁▃▁▁▁▁▁▁▁▁∞▁▁▂▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁∞▁▁▁▁▁▁▁▁▁▁░∞▁▁▁▁▁▁▁▁▁▁▒∞▁▁▁▁▁▁▁▁▁▁▓∞▁▁▁▁▁▁▁▁▁▁█∞▁▁▁▁▁▁▁▁▁▁█░∞▁▁▁▁▁▁▁▁▁█▒∞▁▁▁▁▁▁▁▁▁█▓∞▁▁▁▁▁▁▁▁▁██∞▁▁▁▁▁▁▁▁▁██░∞▁▁▁▁▁▁▁▁██▒∞▁▁▁▁▁▁▁▁██▓∞▁▁▁▁▁▁▁▁███∞▁▁▁▁▁▁▁▁███░∞▁▁▁▁▁▁▁███▒∞▁▁▁▁▁▁▁███▓∞▁▁▁▁▁▁▁████∞▁▁▁▁▁▁▁████░∞▁▁▁▁▁▁████▒∞▁▁▁▁▁▁████▓∞▁▁▁▁▁▁█████∞▁▁▁▁▁▁█████░∞▁▁▁▁▁█████▒∞▁▁▁▁▁█████▓∞▁▁▁▁▁██████∞▁▁▁▁▁██████░∞▁▁▁▁██████▒∞▁▁▁▁██████▓∞▁▁▁▁███████∞▁▁▁▁███████░∞▁▁▁███████▒∞▁▁▁███████▓∞▁▁▁████████∞▁▁▁████████░▁▁▁████████▒▁▁▁████████▓▁▁▁█████████"
     local charwidth=12
     ;;
-  31)
+  22)
     local spin="▐⠂       ▌▐⠈       ▌▐ ⠂      ▌▐ ⠠      ▌▐  ⡀     ▌▐  ⠠     ▌▐   ⠂    ▌▐   ⠈    ▌▐    ⠂   ▌▐    ⠠   ▌▐     ⡀  ▌▐     ⠠  ▌▐      ⠂ ▌▐      ⠈ ▌▐       ⠂▌▐       ⠠▌▐       ⡀▌▐      ⠠ ▌▐      ⠂ ▌▐     ⠈  ▌▐     ⠂  ▌▐    ⠠   ▌▐    ⡀   ▌▐   ⠠    ▌▐   ⠂    ▌▐  ⠈     ▌▐  ⠂     ▌▐ ⠠      ▌▐ ⡀      ▌▐⠠       ▌"
     local charwidth=10
     ;;
-  32)
+  23)
     local spin="█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁████████▁▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁██████████▁▁▁▁▁▁▁▁▁▁███████████▁▁▁▁▁▁▁▁▁█████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁█████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁█████████████▁▁▁▁▁▁▁█████████████▁▁▁▁▁▁▁▁████████████▁▁▁▁▁▁▁▁████████████▁▁▁▁▁▁▁▁▁███████████▁▁▁▁▁▁▁▁▁███████████▁▁▁▁▁▁▁▁▁▁██████████▁▁▁▁▁▁▁▁▁▁██████████▁▁▁▁▁▁▁▁▁▁▁▁████████▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁███████████▁▁▁▁▁▁▁▁▁████████████▁▁▁▁▁▁▁▁████████████▁▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁██████████████▁▁▁▁▁▁██████████████▁▁▁▁▁▁▁▁█████████████▁▁▁▁▁▁▁▁▁████████████▁▁▁▁▁▁▁▁████████████▁▁▁▁▁▁▁▁▁███████████▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁▁█████████▁▁▁▁▁▁▁▁▁▁▁▁████████▁▁▁▁▁▁▁▁▁▁▁▁████████▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁███████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁"
     local charwidth=20
     ;;
+  24)
+    local spin='↑↗→↘↓↙←↖'
+    local charwidth=1
+    ;;
+  25)
+    local spin='⚀⚁⚂⚃⚄⚅⚄⚃⚂⚁'
+    local charwidth=1
+    ;;
+  26)
+    local spin='✶✷✸✹✺✹✸✷'
+    local charwidth=1
+    ;;
+  27)
+    local spin='▁▁▁▁▁▁▂▁▇█▄▂▁▁▁▁▁▁▁▁'
+    local charwidth=1
+    ;;
   esac
 
-  tput civis # cursor invisible
+  tput civis > /dev/tty 2>/dev/null
 
   local i=0
   while kill -0 $pid 2>/dev/null; do
-    local i=$(((i + $charwidth) % ${#spin}))
-    echo -en "\r"
-    # tput cub1
-    printf "%s" "${spin:$i:$charwidth}"
-
+    i=$(( (i + charwidth) % ${#spin} ))
+    printf "\r\033[K%s" "${spin:$i:$charwidth}" > /dev/tty
     sleep .1
   done
 
   cleanup
+  trap - EXIT  # prevent double cleanup on normal exit
 
-  wait $pid # capture exit code
-
+  wait $pid
   return $?
 }
 
+# ── launch ──
 ("$@") &
+bgpid=$!
 
-spinner "${SPINNER:-"$RANDOM"}" $!
+# Kill the background command if the spinner wrapper is terminated
+trap "kill -- $bgpid 2>/dev/null" INT TERM HUP
+
+spinner "${SPINNER:-$RANDOM}" $bgpid
