improve image scripts

diff --git a/scripts/imageDrive b/scripts/imageDrive
--- a/scripts/imageDrive
+++ b/scripts/imageDrive
@@ -1,30 +1,61 @@
 #!/bin/bash
 
-source enforceSudo
+help() {
+	cat <<EOF
+Usage:
+  imageDrive [OPTIONS...]
 
-device=$2
-image=`readlink -f $1`
+Options:
+  -?, -h, --help           Show help (this)
+  -i, --image=<image>      Specifies the image input file
+  -d, --device=<device>    Specifies the device output
+
+EOF
+}
+
+while (( $# > 0 )) ; do
+	case "$1" in
+		-\?|-h|--help)
+			help
+			exit 0
+		;;
+		-i|--image|--image=*)
+			[[ "$1" = --image=* ]] && image="${1#*=}" || { shift; image="$1"; }
+		;;
+		-d|--device|--device=*)
+			[[ "$1" = --device=* ]] && device="${1#*=}" || { shift; device="$1"; }
+		;;
+		*)
+			echo "Unrecgonized option .. For a full list of available options see imageDrive -h"
+			exit 1
+	esac
+	shift
+done
+
+if [ ! "$image" ]; then
+	image=`readlink -f ./*.img`
+else
+	image=`readlink -f $image`
+fi
+
+if [ ! "$image" ]; then
+	echo -e "Could not autodetect an image. Please specify one\n imageDrive \x1b[31m-i <image>\x1b[0m"
+	exit 1
+fi
 
 if [ ! "$device" ]; then
 	device="/dev/$(lsblk -o NAME | grep mmc | head -n 1)";
 fi
 
-if [ ! "$device" ] || [ "$device" = "/dev/" ]; then
+if [ "$device" = "/dev/" ]; then
 	device="/dev/$(lsblk -o NAME | grep sda | head -n 1)";
 fi
 
-lsblk | grep -v snap
+if [ "$device" = "/dev/" ]; then
+	echo -e "Could not autodetect a device. Please specify one\n imageDrive \x1b[31m-d <device>\x1b[0m"
+	exit 1
+fi
 
-echo -e "\nYou are about to write the image '$image' to the device '$device'\nPress enter to continue .. or Ctrl+c to cancel\n"
+lsblk | grep disk
 
-read -p ""
-
-set -x
-
-umount $device
-
-echo "Starting dd @$(date +%F_%H:%M)"
-
-time dd bs=4M if=$image of=$device conv=fdatasync status=progress
-
-sync
+sudo $DOTFILES/scripts/duplicateImage $image $device
